# Generated by Django 5.2 on 2025-04-05 21:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Review', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
